package com.weather.byhieg.easyweather.Db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY_WEATHER".
 */
public class CityWeather {

    private Long id;
    private String cityName;
    private byte[] weatherBean;
    private java.util.Date updateTime;

    public CityWeather() {
    }

    public CityWeather(Long id) {
        this.id = id;
    }

    public CityWeather(Long id, String cityName, byte[] weatherBean, java.util.Date updateTime) {
        this.id = id;
        this.cityName = cityName;
        this.weatherBean = weatherBean;
        this.updateTime = updateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public byte[] getWeatherBean() {
        return weatherBean;
    }

    public void setWeatherBean(byte[] weatherBean) {
        this.weatherBean = weatherBean;
    }

    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

}
