package com.weather.byhieg.easyweather.Db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.weather.byhieg.easyweather.Db.ProvinceDao;
import com.weather.byhieg.easyweather.Db.CityDao;
import com.weather.byhieg.easyweather.Db.CityWeatherDao;
import com.weather.byhieg.easyweather.Db.DirectDao;
import com.weather.byhieg.easyweather.Db.LoveCityDao;
import com.weather.byhieg.easyweather.Db.ViewSpotDao;
import com.weather.byhieg.easyweather.Db.ViewSpotWeatherDao;
import com.weather.byhieg.easyweather.Db.LoveViewSpotDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        ProvinceDao.createTable(db, ifNotExists);
        CityDao.createTable(db, ifNotExists);
        CityWeatherDao.createTable(db, ifNotExists);
        DirectDao.createTable(db, ifNotExists);
        LoveCityDao.createTable(db, ifNotExists);
        ViewSpotDao.createTable(db, ifNotExists);
        ViewSpotWeatherDao.createTable(db, ifNotExists);
        LoveViewSpotDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        ProvinceDao.dropTable(db, ifExists);
        CityDao.dropTable(db, ifExists);
        CityWeatherDao.dropTable(db, ifExists);
        DirectDao.dropTable(db, ifExists);
        LoveCityDao.dropTable(db, ifExists);
        ViewSpotDao.dropTable(db, ifExists);
        ViewSpotWeatherDao.dropTable(db, ifExists);
        LoveViewSpotDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(ProvinceDao.class);
        registerDaoClass(CityDao.class);
        registerDaoClass(CityWeatherDao.class);
        registerDaoClass(DirectDao.class);
        registerDaoClass(LoveCityDao.class);
        registerDaoClass(ViewSpotDao.class);
        registerDaoClass(ViewSpotWeatherDao.class);
        registerDaoClass(LoveViewSpotDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
