package com.weather.byhieg.easyweather.Db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOVE_CITY".
 */
public class LoveCity {

    private Long id;
    private String citynName;
    private Integer order;

    public LoveCity() {
    }

    public LoveCity(Long id) {
        this.id = id;
    }

    public LoveCity(Long id, String citynName, Integer order) {
        this.id = id;
        this.citynName = citynName;
        this.order = order;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCitynName() {
        return citynName;
    }

    public void setCitynName(String citynName) {
        this.citynName = citynName;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

}
