package com.weather.byhieg.easyweather.Db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PROVINCE".
 */
public class Province {

    private Long id;
    /** Not-null value. */
    private String provinceName;

    public Province() {
    }

    public Province(Long id) {
        this.id = id;
    }

    public Province(Long id, String provinceName) {
        this.id = id;
        this.provinceName = provinceName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getProvinceName() {
        return provinceName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

}
