package com.weather.byhieg.easyweather.Db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VIEW_SPOT".
 */
public class ViewSpot {

    private Long id;
    /** Not-null value. */
    private String directName;
    /** Not-null value. */
    private String viewSpotName;
    /** Not-null value. */
    private String viewSpotID;
    private String love;

    public ViewSpot() {
    }

    public ViewSpot(Long id) {
        this.id = id;
    }

    public ViewSpot(Long id, String directName, String viewSpotName, String viewSpotID, String love) {
        this.id = id;
        this.directName = directName;
        this.viewSpotName = viewSpotName;
        this.viewSpotID = viewSpotID;
        this.love = love;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDirectName() {
        return directName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDirectName(String directName) {
        this.directName = directName;
    }

    /** Not-null value. */
    public String getViewSpotName() {
        return viewSpotName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setViewSpotName(String viewSpotName) {
        this.viewSpotName = viewSpotName;
    }

    /** Not-null value. */
    public String getViewSpotID() {
        return viewSpotID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setViewSpotID(String viewSpotID) {
        this.viewSpotID = viewSpotID;
    }

    public String getLove() {
        return love;
    }

    public void setLove(String love) {
        this.love = love;
    }

}
