package com.weather.byhieg.easyweather.Db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "VIEW_SPOT_WEATHER".
 */
public class ViewSpotWeather {

    private Long id;
    private byte[] weatherBean;
    private java.util.Date updateTime;
    private String name;

    public ViewSpotWeather() {
    }

    public ViewSpotWeather(Long id) {
        this.id = id;
    }

    public ViewSpotWeather(Long id, byte[] weatherBean, java.util.Date updateTime, String name) {
        this.id = id;
        this.weatherBean = weatherBean;
        this.updateTime = updateTime;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public byte[] getWeatherBean() {
        return weatherBean;
    }

    public void setWeatherBean(byte[] weatherBean) {
        this.weatherBean = weatherBean;
    }

    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
